### ISSUE TITLE
Does this work with TextFormField?

### ISSUE THREAD

**Issue by jam33** [caseyryan/flutter_focus_watcher#4]
First of all, great package!  I haven't done a ton of testing, but functionality seems sporadic for flutter's TextFormField.  I'd say it works 80% of the time, but randomly doesn't work 20% of the time.  Is this because the library was only written to work on TextField and not TextFormField?  I can provide an example if needed, just wanted to know if this is a known limitation.  Thanks!

**Comment by caseyryan** [comment]
Hi, this package is not required anymore. Flutter can do it of the box now. Simply use CustomScrollView and SliverList for forms. 
If you just need an automatic unfocusing, you can use Unfocuser from my other package https://pub.dev/packages/flutter_multi_formatter
It works fine but from time to time it gets broken because flutter team add some breaking functionality to the new versions of Flutter. I can't do anything with this
